name: 'Datadog Action'
description: 'Push Datadog metrics and events from GitHub Actions'
author: 'Massimiliano Pippi'
inputs:
  api-key:
    description: 'A valid Datadog API Key'
    required: true
  metrics:
    description: 'A list of metrics objects to send, see docs for details'
    default: '[]'
    required: false
  events:
    description: 'A list of event objects to send, see docs for details'
    default: '[]'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bar-chart-2'
  color: 'purple'
