name: 'Datadog Action'
description: 'Push Datadog metrics and events from GitHub Actions'
author: 'Srikanth Nutigattu'
inputs:
  api-key:
    description: 'A valid Datadog API Key'
    required: true

  github-context:
    description: 'Context of github being executed'
    required: false
    default: '{}'

  datadog-region:
    description: 'Region of Datadog instance, value can be either us or eu'
    required: false
    default: 'eu'

  start-timestamp:
    description: 'Timestamp for calculating duration event'
    required: false

  result:
    description: 'Result of the Build'
    required: false
    default: 'NA'

  env-name:
    description: 'Name of the environment the build for'
    required: false
    default: 'NA'

  global-tags:
    description: 'A list of tags (key, values) that you want to apply for all metrics and events'
    default: '[]'
    required: false
  metrics:
    description: 'A list of metrics objects to send, see docs for details'
    default: '[]'
    required: false
  events:
    description: 'A list of event objects to send, see docs for details'
    default: '[]'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bar-chart-2'
  color: 'purple'
